### ISSUE TITLE
requests timeout support

### ISSUE THREAD

**Issue by jhasbani** [twilio/authy-python#52]
We use this library in production, and as a best practice, we wish to make use of timeouts. Per python requests' documentation, "Nearly all production code should use this parameter in nearly all requests.".

Would it be possible to extend `authy.api.resources.Resource` to take an optional `timeout` parameter that is passed through to requests.request? It would need to be piped through from `AuthyApiClient` to the individual `Resource` implementations.

Thanks!

**Comment by robinske** [comment]
Thanks for the issue @jhasbani - I'd definitely take a look at a PR for this if you have one!
