### ISSUE TITLE
SMS OTP standard?

### ISSUE THREAD

**Issue by hampsterx** [twilio/authy-python#53]
hi there,

not a python question directly but is there any plans to support this?

https://www.zdnet.com/article/google-backs-apples-sms-otp-standard-proposal/

Either directly or by allowing the SMS msg format to be specified?

**Comment by robinske** [comment]
We don't have a specific date for this yet, but we are aware and actively collaborating with the people involved with the standard. However any new features would be made to our Verify API (which uses the Twilio python sdk) https://www.twilio.com/docs/verify/api
