### ISSUE TITLE
twilio suspensions 

### ISSUE THREAD

**Issue by williamsj56** [twilio/authy-python#56]
twilio has been a pain in the ass
me and my friend has been trying to work on an app and try different stuff like automating dictionary building dating apps
but when i try upgrading account it gets suspended i tried two accounts it got suspended
i asked my friend to try from his end in germany same thing happened

**Comment by robinske** [comment]
Hey @williamsj56 - sorry to hear that. This is a better question for support, can you email help@twilio.com? I'm going to close the issue but if you leave another comment with the ticket # I can escalate.
