### ISSUE TITLE
[question] is it possible to get the tokens that are available into authy account

### ISSUE THREAD

**Issue by alexzanderr** [twilio/authy-python#58]
here is an example with tokens (accounts) with OTP.
![image](https://user-images.githubusercontent.com/54772464/136623094-d2461e38-6ffa-42a9-a4f9-b078d73455d3.png)

is there a way to list them in python with the title (website) and active token(OTP) ?

i want to make a command line app.

**Comment by robinske** [comment]
hey there, unfortunately that's not possible with the API (and therefore can't be added to the python helper library) and I'm not aware of any plans to add that kind of functionality right now.

in the future you'll get a faster answer by [contacting support](https://support.twilio.com/hc/en-us)!
